version: "3"
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/:/etc/selenoid/"
      - "./videos/:/opt/selenoid/video/"
      - "./logs/:/opt/selenoid/logs/"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./videos
    command: ["-limit", "5", "-container-network", "bridge", "-timeout", "3m"]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
