services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/:/etc/selenoid/:ro"
      - "./video/:/opt/selenoid/video/"
      - "./logs/:/opt/selenoid/logs/"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./video
    command: ["-limit", "5", "-timeout", "3m", "-service-startup-timeout", "2m"]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    networks:
      - selenoid-net
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  selenoid-net:
    driver: bridge
